### ISSUE TITLE
Very large widget which is larger than the viewport never fires impression event

### ISSUE THREAD

**Issue by yfujiki** [623637646/flutter_impression#1]
Thank you for this library. I want to use this but facing one issue.

If the widget is very large, then it never fires impression event. 

For example, I changed the height of the demo_list_view.dart to be 3000 instead of 100.
<img width="541" alt="CleanShot 2023-10-30 at 17 23 00@2x" src="https://github.com/623637646/flutter_impression/assets/879725/f1ab86c1-1eca-4255-9846-182d1e76b248">

No matter how long you stay on a list item, the impression event never fires.

https://github.com/623637646/flutter_impression/assets/879725/ddd95e92-4f27-472d-980d-dd70fa3194e1

I think, if the widget is covering the entire viewport of the parent scrollview, then it should consider the visibility is 100%.
Not sure how we can achieve this 🤔 but hopefully you get the idea.

**Comment by 623637646** [comment]
Thanks for your question. 

I spent some time thinking about your question. The field `visibleFractionThreshold` means "The threshold of the visible area ratio of the current widget". If the widget is much bigger than the screen. The visible fraction ratio will never reach the threshold. It is expected. 

For your case, you may add the ImpressionDetector on the top of the ScrollView. Let the ScrollVeiw be the child of ImpressionDetector. I think this can satisfy your case.
